name = "weclaw-send"
compatibility_date = "2026-07-21"
pages_build_output_dir = "_site"

[[analytics_engine_datasets]]
binding = "DOWNLOADS"
dataset = "weclawsend_downloads"

[[analytics_engine_datasets]]
binding = "UPDATE_CHECKS"
dataset = "weclawsend_update_checks"
